### ISSUE TITLE
[question] Is there an alternative to select multiple?

### ISSUE THREAD

**Issue by somenxavier** [maxmert/maxmertkit#86]
Hi,

First of all, thanks for create maxmerkit. It's useful and lightweight.

I just want to know if it's possible to emulate the select multiple alternative of [w2ui](http://davidwalsh.name/demo/html5-input-types-alternative.php) (section Multi-Select Drop Down Lists).

Thanks a lot,

**Comment by maxmert** [comment]
Hello. Unfortunately not from the box, sorry. I have it in TODO list, but it not the first in priority

**Comment by somenxavier** [comment]
What a pitty! Can you recommend some code for emulate this. So lightful as maxmerkit?

**Comment by somenxavier** [comment]
Mark as wishlist
